##-----------------------------------------------------------------------------------------------
## Web Maps Connector (which shows web maps as layers in Smallworld(TM) Core Spatial Technology)
## Copyright (C) 2017 KUBRA
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http:##www.gnu.org/licenses/>.
##
## You may contact KUBRA at https://kubra.com/contact-us/
##-----------------------------------------------------------------------------------------------
:opacity_slider	100
:legend_label	Legends
:quit	Quit
:about	About

:apply_maps   Apply changes to Main GIS maps

:clear_selection   Clear Selection

:hide_map_chooser  Hide Map Chooser

:large_icons  Thumbnails

:show_map_list     Map List
:small_icons       Icons

:table        Tabular list

:|basemapat_dataset-road_tile|             basemap.at Road
:|bing_dataset-aerial_labelled_tile|       Bing Aerial Labelled
:|bing_dataset-aerial_tile|                Bing Aerial
:|bing_dataset-road_tile|                  Bing Road
:|bing_dataset-traffic_tile|               Bing Traffic
:|birdseye_dataset-birdseye|               Bird's Eye
:|birdseye_dataset-birdseye_labelled|      Bird's Eye Labelled
:|google_dataset-aerial_labelled_tile|     Google Aerial Labelled
:|google_dataset-aerial_tile|              Google Aerial
:|google_dataset-road_tile|                Google Road
:|google_dataset-terrain_tile|             Google Terrain
:|mapquest_dataset-tile|                   MapQuest Open Road
:|mapquest_dataset-aerial_tile|            MapQuest Open Tile
:|spatialstream_dataset-tile|              SpatialStream
:|spatialenergy_dataset-nationwide_prime|  SE Nationwide Prime
:|osm_dataset-cyclemap_tile|               OSM (cycle)
:|osm_dataset-mapnik_tile|                 OSM (mapnik)
:|osm_dataset-osmarender_tile|             OSM (osmarender)
:|weatherbug_dataset-doppler_radar|        WeatherBug Doppler Radar
:|weatherbug_dataset-lightning_strikes|    WeatherBug Lightning Strikes
:|custom-uservoice|                        Feedback
:|wms_dataset-ktimanet_tile|        KTIMANET (WMS)
:|arcgis_dataset-world_street_map|        World Street Map
:|arcgis_dataset-world_imagery|        World Imagery








