#% text_encoding = iso8859_1
##-----------------------------------------------------------------------------------------------
## Web Maps Connector (which shows web maps as layers in Smallworld(TM) Core Spatial Technology)
## Copyright (C) 2017 KUBRA
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http:##www.gnu.org/licenses/>.
##
## You may contact KUBRA at https://kubra.com/contact-us/
##-----------------------------------------------------------------------------------------------

   
:get_metadata	    Get Image Information
:get_metadata_sh    Get Information for image at map center point
:get_metadata_tt    Get Information for image at map center point

:toggle_dataset      		 Dataset?
:toggle_dataset_close_tt	 Close Web Maps Connector Dataset
:toggle_dataset_close_sh	 Close Web Maps Connector Dataset
:toggle_dataset_open_tt	 	 Open Web Maps Connector Dataset
:toggle_dataset_open_sh	 	 Open Web Maps Connector Dataset

:geocode	    Geocode
:geocode_sh	    Geocode the Query String 
:geocode_tt	    Geocode the Query String 

:bing_traffic	    Traffic
:bing_traffic_sh	    Bing Traffic
:bing_traffic_tt	    Bing Traffic

:google_geocode	    Geocode
:google_geocode_sh  Geocode the Query String 
:google_geocode_tt  Geocode the Query String 

:weatherbug_toggle_radar    	WeatherBug Radar
:weatherbug_toggle_radar_sh	WeatherBug Radar
:weatherbug_toggle_radar_tt	WeatherBug Radar

:reverse_geocode	    Reverse Geocode
:reverse_geocode_sh	    Reverse Geocode the current Trail Point
:reverse_geocode_tt	    Reverse Geocode the current Trail Point

:google_reverse_geocode	    Reverse Geocode
:google_reverse_geocode_sh  Reverse Geocode the current Trail Point
:google_reverse_geocode_tt  Reverse Geocode the current Trail Point

:show_in_web_browser	    Web Browser
:show_in_web_browser_sh	    Launch maps.bing.com with the current map view
:show_in_web_browser_tt	    Launch maps.bing.com with the current map view

:google_show_in_web_browser	    Web Browser
:google_show_in_web_browser_sh	    Launch maps.google.com with the current map view
:google_show_in_web_browser_tt	    Launch maps.google.com with the current map view

:route_finder	    	    Route Finder
:route_finder_sh	    Open Route Finder Dialog
:route_finder_tt	    Open Route Finder Dialog

:get_osm_data	    	    Get OSM Data
:get_osm_data_sh	    Retrieve Vector OSM Data
:get_osm_data_tt	    Retrieve Vector OSM Data

:get_osm_streets_only	    Get OSM Streets Only
:get_osm_streets_only_sh    Retrieve Vector OSM Streets Only
:get_osm_streets_only_tt    Retrieve Vector OSM Streets Only

:get_spatialstream_parcel_data	    	    Get Parcel Data
:get_spatialstream_parcel_data_sh	    Retrieve Vector Parcel Data
:get_spatialstream_parcel_data_tt	    Retrieve Vector Parcel Data

:launch_osm	    	    Show in OSM
:launch_osm_sh	    	    Launch default browser with OpenStreetMap.org
:launch_osm_tt	    	    Launch default browser with OpenStreetMap.org

:launch_josm	    	    Show in JOSM
:launch_josm_sh	    	    Download OSM data into an open JOSM session
:launch_josm_tt	    	    Download OSM data into an open JOSM session

:launch_mapzen	    	    Show in Mapzen
:launch_mapzen_sh	    Launch default browser with mapzen.cloudmade.com
:launch_mapzen_tt	    Launch default browser with mapzen.cloudmade.com



:show_birds_eye_in_web_browser	    	Bird's Eye
:show_birds_eye_in_web_browser_sh	Launch Bird's Eye view in maps.bing.com with the current map view
:show_birds_eye_in_web_browser_tt	Launch Bird's Eye view in maps.bing.com with the current map view
:show_birds_eye_in_web_browser_close_sh	Zoom in closer to enable Bird's Eye view
:show_birds_eye_in_web_browser_close_tt	Zoom in closer to enable Bird's Eye view

:stop_acp	    	    Stop WMC ACP
:stop_acp_sh	    	    Kill the WMC ACP process
:stop_acp_tt	    	    Kill the WMC ACP process

:load_birdseye_shift_cache	    	    Load BirdsEye Cache...
:load_birdseye_shift_cache_sh	    	    Load BirdsEye Cache
:load_birdseye_shift_cache_tt	    	    Load BirdsEye Cache

:save_birdseye_shift_cache	    	    Save BirdsEye Cache...
:save_birdseye_shift_cache_sh	    	    Save BirdsEye Cache
:save_birdseye_shift_cache_tt	    	    Save BirdsEye Cache

:rotate_map_north	    North
:rotate_map_north_sh	    Rotate map view to the North
:rotate_map_north_tt	    Rotate map view to the North

:rotate_map_south	    South
:rotate_map_south_sh	    Rotate map view to the South
:rotate_map_south_tt	    Rotate map view to the South

:tilt_map	    	    Tilt Map
:tilt_map_sh	    	    Tilts the Map for Bird's Eye View
:tilt_map_tt	    	    Tilts the Map for Bird's Eye View

:adjust_birdseye_shift	    Adjust Birdseye Shift
:adjust_birdseye_shift_sh   Adjust Birdseye Shift based on current trail
:adjust_birdseye_shift_tt   Adjust Birdseye Shift based on current trail

:adjust_birdseye_shift_half_trail      Adjust Birdseye Shift (Half Trail Length)
:adjust_birdseye_shift_half_trail_sh   Adjust Birdseye Shift based on half the current trail length
:adjust_birdseye_shift_half_trail_tt   Adjust Birdseye Shift based on half the current trail length

:reset_birdseye_shift	   Reset Birdseye Shift
:reset_birdseye_shift_sh   Reset Birdseye Shift
:reset_birdseye_shift_tt   Reset Birdseye Shift


:place_trail_point  Place Trail Point

:query_sh	    Enter Search/Geocode String
:query_tt	    Enter Search/Geocode String

:road_view	    Road
:road_view_off_tt   Switch to road view
:road_view_off_sh   Switch to road view
:road_view_on_tt    Turn off road view
:road_view_on_sh    Turn off road view

:road_transparent_view	    Road(T)
:road_transparent_view_off_tt   Switch to road transparent view
:road_transparent_view_off_sh   Switch to road transparent view
:road_transparent_view_on_tt    Turn off road transparent view
:road_transparent_view_on_sh    Turn off road transparent view

:aerial_view	    Aerial
:aerial_view_off_tt Switch to aerial view
:aerial_view_off_sh Switch to aerial view
:aerial_view_on_tt  Turn off aerial view
:aerial_view_on_sh  Turn off aerial view

:label_view?	    Label View?
:label_view_on_tt   Hide labels
:label_view_on_sh   Hide labels
:label_view_off_tt  Show labels
:label_view_off_sh  Show labels


:about		    About
:about_tt	    About Web Maps Connector, Terms of Use and Privacy Policy
:about_sh           About Smallworld Web Maps Connector, Terms of Use and Privacy Policy

:ve_som_about_dialog	  About Web Maps Connector

:ve_reverse_geocode_result   Reverse Geocode Result for current trail point

#1

:close                    Close
:save_to_clipboard        Save to Clipboard
:show_address_in_browser  Show Address in Browser


:updates_remind_me_later Remind me later
:updates_download	 Download Revision #1...
:revision_up_to_date	 Web Maps Connector

Your current revision '#1' is the most recent one available.

:more_recent_revision_exists Web Maps Connector

Your current revision is '#1'.  A more recent revision '#2' is available for download.

:query_help_string    Enter Search/Geocode String 
