#% text_encoding = iso8859_1
##-----------------------------------------------------------------------------------------------
## Web Maps Connector (which shows web maps as layers in Smallworld(TM) Core Spatial Technology)
## Copyright (C) 2017 KUBRA
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http:##www.gnu.org/licenses/>.
##
## You may contact KUBRA at https://kubra.com/contact-us/
##-----------------------------------------------------------------------------------------------

   
:environment_changed	You have toggled the production/staging environment.  Please review the Microsoft Terms of Use at http://www.microsoft.com/virtualearth/assets/docs/mappoint-terms.aspx.

:no_sw_auth_type	No authorisation information is defined for the Bing Maps Connector.
:sw_auth_modify_and_compile	You can modify the following code and run it at the MagikSF prompt to modify your authorisation settings:
#1

:route_default_start_label	Start
:route_default_end_label	End
:route_default_intermediate_label	Stop ###1

:default_point_title_string 		   Smallworld Map Centre