#% text_encoding = iso8859_1
##-----------------------------------------------------------------------------------------------
## Web Maps Connector (which shows web maps as layers in Smallworld(TM) Core Spatial Technology)
## Copyright (C) 2017 KUBRA
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http:##www.gnu.org/licenses/>.
##
## You may contact KUBRA at https://kubra.com/contact-us/
##-----------------------------------------------------------------------------------------------


:title			About Smallworld Virtual Earth Connector
   
:label_item_01		Smallworld Virtual Earth Connector is created by iFactor Consulting, Inc.

:ifactor_consulting	http://www.ifactorconsulting.com
:ifactor_consulting_url	http://www.ifactorconsulting.com

:check_for_updates_label  You are currently using product revision: #1
:check_for_updates_button Check for Updates...

:label			By using this functionality you agree to have read and understood the following Terms of Use and Privacy Policy.
This application may collect information on the IP address and user requests during use.
See the full Microsoft Privacy Policy for more information.

:terms_of_use		Terms of Use
:terms_of_use_url	http://www.microsoft.com/virtualearth/assets/docs/mappoint-terms.aspx

:privacy_policy		Full Privacy Policy
:privacy_policy_url	http://privacy.microsoft.com/en-us/fullnotice.mspx

:check_updates          Check for Updates...

:support_info		If you need assistance with installation or use of the product, please email support@ifactor.zendesk.com or visit http://support.ifactorconsulting.com. 

:send_support_email     support@ifactor.zendesk.com
:goto_support_page      http://support.ifactorconsulting.com
:goto_support_page_url	http://support.ifactorconsulting.com
