#% text_encoding = iso8859_1
##-----------------------------------------------------------------------------------------------
## Web Maps Connector (which shows web maps as layers in Smallworld(TM) Core Spatial Technology)
## Copyright (C) 2017 KUBRA
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http:##www.gnu.org/licenses/>.
##
## You may contact KUBRA at https://kubra.com/contact-us/
##-----------------------------------------------------------------------------------------------

   
:get_metadata	    Get Image Information
:get_metadata_sh    Get Information for image at map center point
:get_metadata_tt    Get Information for image at map center point

:toggle_dataset      		 Dataset?
:toggle_dataset_close_tt	 Close Virtual Earth Dataset
:toggle_dataset_close_sh	 Close Virtual Earth Dataset
:toggle_dataset_open_tt	 	 Open Virtual Earth Dataset
:toggle_dataset_open_sh	 	 Open Virtual Earth Dataset

:geocode	    Geocode
:geocode_sh	    Geocode the Query String 
:geocode_tt	    Geocode the Query String 

:reverse_geocode	    Reverse Geocode
:reverse_geocode_sh	    Reverse Geocode the current Trail Point
:reverse_geocode_tt	    Reverse Geocode the current Trail Point

:show_in_web_browser	    Web Browser
:show_in_web_browser_sh	    Launch maps.live.com with the current map view
:show_in_web_browser_tt	    Launch maps.live.com with the current map view

:show_birds_eye_in_web_browser	    	Bird's Eye
:show_birds_eye_in_web_browser_sh	Launch Bird's Eye view in maps.live.com with the current map view
:show_birds_eye_in_web_browser_tt	Launch Bird's Eye view in maps.live.com with the current map view

:place_trail_point  Place Trail Point

:query_sh	    Enter Search/Geocode String
:query_tt	    Enter Search/Geocode String

:road_view	    Road
:road_view_off_tt   Switch to road view
:road_view_off_sh   Switch to road view
:road_view_on_tt    Turn off road view
:road_view_on_sh    Turn off road view

:aerial_view	    Aerial
:aerial_view_off_tt Switch to aerial view
:aerial_view_off_sh Switch to aerial view
:aerial_view_on_tt  Turn off aerial view
:aerial_view_on_sh  Turn off aerial view

:label_view?	    Label View?
:label_view_on_tt   Hide labels
:label_view_on_sh   Hide labels
:label_view_off_tt  Show labels
:label_view_off_sh  Show labels


:about		    About
:about_tt	    About Smallworld Virtual Earth Connector, Terms of Use and Privacy Policy
:about_sh           About Smallworld Virtual Earth Connector, Terms of Use and Privacy Policy

:ve_som_about_dialog	  About Smallworld Virtual Earth Connector

:ve_reverse_geocode_result   Reverse Geocode Result for current trail point

#1

:close                    Close
:save_to_clipboard        Save to Clipboard
:show_address_in_browser  Show Address in Browser


:updates_remind_me_later Remind me later
:updates_download	 Download Revision #1...
:revision_up_to_date	 Virtual Earth Connector for Smallworld

Your current revision '#1' is the most recent one available.

:more_recent_revision_exists Virtual Earth Connector for Smallworld

Your current revision is '#1'.  A more recent revision '#2' is available for download.

:query_help_string    Enter Search/Geocode String 
:default_point_title_string 		   Smallworld Map Center