##-----------------------------------------------------------------------------------------------
## Web Maps Connector (which shows web maps as layers in Smallworld(TM) Core Spatial Technology)
## Copyright (C) 2017 KUBRA
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http:##www.gnu.org/licenses/>.
##
## You may contact KUBRA at https://kubra.com/contact-us/
##-----------------------------------------------------------------------------------------------
:quit			Quit
:calculate_route	Calculate route
:about			About

:title			WMC Route Finder
:main			Main
:waypts_label		Waypoints
:results_label         Route Description

:add_selected          Add selected RWOs as waypoints
:add_trail_pts         Add trail points as waypoints
:reverse_waypts        Reverse order of waypoints
:clear_waypts          Clear waypoints
:sort_waypts           Sort waypoints
:roundtrip_waypts      Create roundtrip
:save_waypts           Save waypoints...
:load_waypts           Load waypoints...

:add_before            Add waypoints before
:add_after             Add waypoints after
:goto_waypt	       Go to waypoint
:flash_waypt	       Flash waypoint
:move_waypt_top        Move waypoint to top
:move_waypt_up         Move waypoint up
:move_waypt_down       Move waypoint down
:move_waypt_bottom     Move waypoint bottom
:remove_waypt          Remove waypoint

:zoom_to_route		Zoom to route
:set_trail_from_route	Set trail from route
:save_results		Save results to file ...
:clear_results		Clear results
:flash_direction	Flash direction
:goto_direction		Go to direction
:distance_units		Distance units
:mile			Miles
:km			Kilometers

:show_in_web_browser	    View in Web Browser
:show_in_web_browser_sh	    Launch maps.live.com with the current map view
:show_in_web_browser_tt	    Launch maps.live.com with the current map view

:show_birds_eye_in_web_browser	    	View Bird's Eye
:show_birds_eye_in_web_browser_sh	Launch Bird's Eye view in maps.live.com with the current map view
:show_birds_eye_in_web_browser_tt	Launch Bird's Eye view in maps.live.com with the current map view

:options		Options
:route_style		Route style
:route_style_color	Route color
:route_style_width	Route width
:route_style_dash	Route dash pattern
:wp_style		Waypoint style
:show_waypoint_labels	Show waypoint labels?
:wp_style_color		Waypoint color
